# Generated by Django 3.1.5 on 2021-01-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
